// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511101023_InitialFixed")]
    partial class InitialFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Booking", b =>
                {
                    b.Property<int>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Booking_ID"));

                    b.Property<DateTime>("B_Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("B_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client_Contacts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Players_Count")
                        .HasColumnType("int");

                    b.Property<int>("Session_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Session_ID1")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Booking_ID");

                    b.HasIndex("Session_ID1");

                    b.HasIndex("User_ID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("WebApplication1.Models.Quest", b =>
                {
                    b.Property<int>("Quest_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Quest_ID"));

                    b.Property<decimal>("Base_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Difficulty_Level")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Max_Players")
                        .HasColumnType("int");

                    b.Property<int>("Min_Players")
                        .HasColumnType("int");

                    b.Property<string>("Q_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Q_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.HasKey("Quest_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Quest");
                });

            modelBuilder.Entity("WebApplication1.Models.Review", b =>
                {
                    b.Property<int>("Review_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Review_ID"));

                    b.Property<int?>("ClientUser_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("R_Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Room_ID")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Review_ID");

                    b.HasIndex("ClientUser_ID");

                    b.HasIndex("Room_ID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("WebApplication1.Models.Room", b =>
                {
                    b.Property<int>("Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_ID"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Availability_Status")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Owner_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("QR_Creation_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("QR_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QR_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Room_ID");

                    b.HasIndex("Owner_ID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("WebApplication1.Models.Session", b =>
                {
                    b.Property<int>("Session_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Session_ID"));

                    b.Property<int>("Quest_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Quest_ID1")
                        .HasColumnType("int");

                    b.Property<decimal?>("S_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("S_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Start_DateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Session_ID");

                    b.HasIndex("Quest_ID1");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Account_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Registration_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Booking", b =>
                {
                    b.HasOne("WebApplication1.Models.Session", "Session")
                        .WithMany("Booking")
                        .HasForeignKey("Session_ID1");

                    b.HasOne("WebApplication1.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WebApplication1.Models.Quest", b =>
                {
                    b.HasOne("WebApplication1.Models.Room", "Room")
                        .WithMany("Quests")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebApplication1.Models.Review", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientUser_ID");

                    b.HasOne("WebApplication1.Models.Room", "Room")
                        .WithMany("Review")
                        .HasForeignKey("Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("WebApplication1.Models.Room", b =>
                {
                    b.HasOne("WebApplication1.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("Owner_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WebApplication1.Models.Session", b =>
                {
                    b.HasOne("WebApplication1.Models.Quest", "Quest")
                        .WithMany("Session")
                        .HasForeignKey("Quest_ID1");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("WebApplication1.Models.Quest", b =>
                {
                    b.Navigation("Session");
                });

            modelBuilder.Entity("WebApplication1.Models.Room", b =>
                {
                    b.Navigation("Quests");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("WebApplication1.Models.Session", b =>
                {
                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
